"""Profile the raw data and write docs/data_quality_profile.md.

Usage:
    python -m src.etl.profile
"""
from __future__ import annotations

import logging

import pandas as pd

from .config import DOCS, NON_PRODUCT_CODES, NON_PRODUCT_PREFIXES
from .extract import extract

KEY = ["invoice", "stock_code", "description", "quantity", "invoice_ts", "unit_price", "customer_id", "country"]


def is_non_product(codes: pd.Series) -> pd.Series:
    return codes.isin(NON_PRODUCT_CODES) | codes.str.startswith(NON_PRODUCT_PREFIXES, na=False)


def profile(df: pd.DataFrame) -> list[tuple[str, int, str]]:
    n = len(df)
    cancel = df.invoice.str.startswith("C", na=False)
    within_dups = sum(g.duplicated(subset=KEY).sum() for _, g in df.groupby("source_sheet"))
    cross_dups = df.duplicated(subset=KEY).sum() - within_dups
    return [
        ("Rows in the workbook (2 sheets)", n, "Starting point"),
        ("Rows repeated in both sheets (1–9 Dec 2010)", cross_dups, "The two sheets overlap; a naive concat double-counts these days"),
        ("Exact duplicate rows within a sheet", within_dups, "Same invoice line recorded twice"),
        ("Cancellation lines (invoice starts with C)", int(cancel.sum()), "Returns/cancellations; kept separately, not as sales"),
        ("Non-sale stock adjustments (qty ≤ 0, invoice not C)", int(((df.quantity <= 0) & ~cancel).sum()), "Inventory write-offs, often with no description"),
        ("Bad-debt adjustments (invoice starts with A)", int(df.invoice.str.startswith("A", na=False).sum()), "Accounting entries, negative prices"),
        ("Non-product stock codes (postage, fees, tests…)", int(is_non_product(df.stock_code).sum()), "Not merchandise; excluded from product sales"),
        ("Lines with unit price = 0", int((df.unit_price == 0).sum()), "Free items or data errors"),
        ("Lines without customer ID", int(df.customer_id.isna().sum()), "Guest checkouts; kept for revenue, excluded from customer metrics"),
        ("Lines without description", int(df.description.isna().sum()), "Description is filled from the product's most common name"),
        ("Stock codes with more than one description", int((df.groupby("stock_code").description.nunique() > 1).sum()), "Product names change over time; one canonical name is chosen"),
    ]


def write_markdown(rows: list[tuple[str, int, str]], df: pd.DataFrame) -> None:
    n = len(df)
    lines = [
        "# Data quality profile: raw data",
        "",
        f"Source: UCI Online Retail II · {df.invoice_ts.min():%Y-%m-%d} to {df.invoice_ts.max():%Y-%m-%d} · "
        f"{df.country.nunique()} countries. Generated by `python -m src.etl.profile`.",
        "",
        "| Check | Rows | % of rows | Why it matters / how it is handled |",
        "|---|--:|--:|---|",
    ]
    for label, count, note in rows:
        lines.append(f"| {label} | {count:,} | {count / n:.2%} | {note} |")
    DOCS.mkdir(exist_ok=True)
    (DOCS / "data_quality_profile.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    df = extract()
    rows = profile(df)
    write_markdown(rows, df)
    for label, count, _ in rows:
        print(f"{count:>10,}  {label}")


if __name__ == "__main__":
    main()
