"""Write docs/data_quality_report.md: what the pipeline removed, how lines were classified, what was loaded."""
from __future__ import annotations

import pandas as pd

from .config import DOCS
from .transform import CleaningLog, drop_sheet_overlap


def write_report(raw: pd.DataFrame, clean: pd.DataFrame, clog: CleaningLog, load_stats: dict | None) -> None:
    overlap = raw.drop(drop_sheet_overlap(raw).index)
    overlap_rev = (overlap["quantity"] * overlap["unit_price"]).sum()
    by_type = clean.groupby("line_type").agg(lines=("line_hash", "size"), revenue=("revenue", "sum"))
    lines = [
        "# Data quality report: pipeline run", "",
        f"Generated by `python -m src.etl.pipeline` on {pd.Timestamp.now():%Y-%m-%d %H:%M}.", "",
        "## 1. Cleaning steps", "",
        "| Step | Rows before | Rows after | Removed |", "|---|--:|--:|--:|",
    ]
    lines += [f"| {s} | {b:,} | {a:,} | {b - a:,} |" for s, b, a in clog.steps]
    lines += [
        "", f"> The sheet overlap alone would have double-counted **£{overlap_rev:,.0f}** of revenue (1-9 Dec 2010) in a naive concat.",
        "", "## 2. Line classification", "",
        "| Line type | Lines | Revenue (£) | Meaning |", "|---|--:|--:|---|",
    ]
    meaning = {"sale": "Merchandise sold", "return": "Cancellations (invoice starts with C, negative qty)",
               "fee": "Postage, marketplace fees, bank charges, tests", "adjustment": "Stock and accounting adjustments",
               "zero_price": "Lines with unit price 0"}
    for t, r in by_type.sort_values("lines", ascending=False).iterrows():
        lines.append(f"| {t} | {int(r.lines):,} | {r.revenue:,.0f} | {meaning[t]} |")
    lines += ["", "## 3. Validation", "", "All Pandera checks passed (schema in `src/etl/validate.py`).", ""]
    if load_stats:
        lines += ["## 4. Load", "", f"- Watermark before run: `{load_stats['watermark']}`",
                  f"- Candidate rows: {load_stats['candidates']:,}", f"- Inserted rows: {load_stats['inserted']:,}",
                  f"- Rows in `fact_sales_line` after run: {load_stats['total']:,}", ""]
    DOCS.mkdir(exist_ok=True)
    (DOCS / "data_quality_report.md").write_text("\n".join(lines), encoding="utf-8")
